RESPONSES = [
    "ye one sec",
    "hold on",
    "gimme a moment",
    "on it pal",
    "say less",
    "working on it chill",
    "bro im going as fast as i can",
    "okok relax",
    "gimme a sec im lagging",
    "you think im fast? im a bot not the flash",
    "processing... jk i just had to think about it",
    "k",
    "sure whatever you say",
    "do i look like i get paid for this",
    "fine but you owe me one",
    "uhhh yeah i can do that i think",
    "was already gonna do it",
    "nah",
    "pinging me for ts?",
    "ya",
    "alr dont rush me",
    "sure",
    "yeah yeah yeah",
    "bro thinks im chatgpt",
    "why do i even bother",
    "respectfully... aight",
    "say please",
]